modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "catchlevelcap"
version = "${version}"
displayName = "Cobblemon Catch Level Cap"
authors = "Sylvonir"
description = '''
A simple mod to prevent catching Pokemon too far above your party's level.
'''
#logoFile = ""

[[dependencies.catchlevelcap]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catchlevelcap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catchlevelcap]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.examplemod]]
#modId = "architectury"
#mandatory = true
#versionRange = "[9.1.12,)"
#ordering = "AFTER"
#side = "BOTH"