modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Sylvonir/catchlevelcap/issues"
license = "MPL-2.0"

[[mods]]
modId = "catchlevelcap"
version = "${version}"
displayName = "Cobblemon Catch Level Cap"
displayURL = "https://modrinth.com/mod/catchlevelcap"
authors = "Sylvonir"
description = '''
A simple mod to prevent catching Pokemon too far above your party's level.
'''
logoFile = "icon.png"

[[dependencies.catchlevelcap]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catchlevelcap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catchlevelcap]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5,)"
ordering = "NONE"
side = "BOTH"